swagger: "2.0"

info:
  title: busroutes
  version: 0.0.1

schemes:
  - http

consumes:
  - application/json

produces:
  - application/json

definitions:
  Bus:
    properties:
      id:
        description: Идентификатор автобуса
        type: integer
        example: 111
      city:
        description: Название города
        type: string
        example: Казань
      num:
        description: Номер автобуса
        type: string
        example: 35А
  BusNoID:
    properties:
      city:
        description: Название города
        type: string
        example: Казань
      num:
        description: Номер автобуса
        type: string
        example: 35А
  City:
    properties:
      id:
        description: Идентификатор города
        type: integer
        example: 50
      name:
        description: Название города
        type: string
        example: Казань
  CityNoID:
    properties:
      name:
        description: Название города
        type: string
        example: Казань
  Stop:
    properties:
      id:
        description: Идентификатор остановки
        type: integer
        example: 50
      city:
        description: Название города
        type: string
        example: Казань
      address:
        description: Адрес остановки
        type: string
        example: ул. Пушкина, 62
  StopNoID:
    properties:
      city:
        description: Название города
        type: string
        example: Казань
      address:
        description: Адрес остановки
        type: string
        example: ул. Пушкина, 62
  Route:
    properties:
      bus_id:
        description: Идентификатор автобуса
        type: integer
        example: 50
      stop_id:
        description: Идентификатор остановки
        type: integer
        example: 50
      step:
        description: Порядковый номер остановки на пути автобуса
        type: integer
        example: 1

tags:
  - name: internal
    description: Internal routes
  - name: buses
    description: All about buses
  - name: cities
    description: All about cities
  - name: stops
    description: All about stops
  - name: routes
    description: All about routes

paths:
  /internal/health:
    get:
      summary: Health
      tags:
        - internal
      responses:
        "200":
          description: Success
        "500":
          description: Internal Server Error
  /api/v1/buses:
    get:
      summary: Получение списка действующих автобусов
      tags:
        - buses
      parameters:
        - name: ids
          description: Идентификаторы автобусов
          in: query
          type: array
          items:
            type: integer
          required: false
        - name: cities
          description: Города интересующих автобусов
          in: query
          type: array
          items:
            type: string
          required: false
        - name: nums
          description: Номера автобусов
          in: query
          type: array
          items:
            type: string
          required: false
        - name: limit
          in: query
          description: Пейджинг - выводить N первых автобусов (по умолчанию 20)
          type: integer
        - name: offset
          in: query
          description: Пейджинг - пропустить N первых автобусов
          type: integer
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Bus"
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Добавление новых автобусов
      tags:
        - buses
      parameters:
        - name: buses
          in: body
          description: Автобусы
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/BusNoID"
            example: [{ city: Москва, num: "11" }, { city: Москва, num: "15" }]
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
        "500":
          description: Internal server error

  /api/v1/cities:
    get:
      summary: Получение списка городов
      tags:
        - cities
      parameters:
        - name: ids
          description: Идентификаторы городов
          in: query
          type: array
          items:
            type: integer
          required: false
        - name: names
          description: Названия городов
          in: query
          type: array
          items:
            type: string
          required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/City"
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Добавление новых городов
      tags:
        - cities
      parameters:
        - name: cities
          description: Города
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/CityNoID"
            example: [{ name: Москва }, { name: Казань }, { name: Ижевск }]
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
        "500":
          description: Internal server error
    put:
      summary: Редактирование города
      tags:
        - cities
      parameters:
        - name: city
          description: Город
          in: body
          required: true
          schema:
            $ref: "#/definitions/City"
            example: { id: 1, name: Калуга }
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      summary: Удаление города
      tags:
        - cities
      parameters:
        - name: id
          description: Идентификатор города
          in: query
          type: integer
          required: false
        - name: name
          description: Название города
          in: query
          type: string
          required: false
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
        "500":
          description: Internal server error

  /api/v1/stops:
    get:
      summary: Получение списка остановок
      tags:
        - stops
      parameters:
        - name: ids
          description: Идентификаторы остановок
          in: query
          type: array
          items:
            type: integer
          required: false
        - name: cities
          description: Названия городов
          in: query
          type: array
          items:
            type: string
          required: false
        - name: addresses
          description: Адреса остановок
          in: query
          type: array
          items:
            type: string
          required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Stop"
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Добавление новых остановок
      tags:
        - stops
      parameters:
        - name: stops
          description: Остановки
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/StopNoID"
            example:
              [
                { city: Москва, address: "ул. Пушкина, 62" },
                { city: Ижевск, address: "ул. Жукова, 17" },
              ]
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
        "500":
          description: Internal server error
    put:
      summary: Редактирование остановки
      tags:
        - stops
      parameters:
        - name: stop
          description: Остановка
          in: body
          required: true
          schema:
            $ref: "#/definitions/Stop"
            example: { id: 1, city: Калуга, address: "ул. Никитина, 10" }
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      summary: Удаление остановки
      tags:
        - stops
      parameters:
        - name: id
          description: Идентификатор остановки
          in: query
          type: integer
          required: false
        - name: address
          description: Адрес остановки
          in: query
          type: string
          required: false
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
        "500":
          description: Internal server error

  /api/v1/routes:
    get:
      summary: Получение списка путей автобусов
      tags:
        - routes
      parameters:
        - name: bus_ids
          description: Идентификаторы автобусов
          in: query
          type: array
          items:
            type: integer
          required: false
        - name: stop_ids
          description: Идентификаторы остановок
          in: query
          type: array
          items:
            type: integer
          required: false
        - name: steps
          description: Порядковые номера остановок на пути автобуса
          in: query
          type: array
          items:
            type: integer
          required: false
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Route"
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      summary: Добавление новых путей автобусов
      tags:
        - routes
      parameters:
        - name: routes
          description: Пути автобусов
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/Route"
            example:
              [
                { bus_id: 1, stop_id: 1, step: 1 },
                { bus_id: 1, stop_id: 5, step: 2 },
                { bus_id: 1, stop_id: 17, step: 3 },
              ]
      responses:
        "201":
          description: Created
        "400":
          description: Bad request
        "500":
          description: Internal server error
    put:
      summary: Редактирование пути автобуса
      tags:
        - routes
      parameters:
        - name: route
          description: Путь автобуса
          in: body
          required: true
          schema:
            $ref: "#/definitions/Route"
            example: { bus_id: 1, stop_id: 10, step: 1 }
            required:
              - bus_id
              - stop_id
              - step
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      summary: Удаление пути автобуса
      tags:
        - routes
      parameters:
        - name: bus_id
          description: Идентификатор автобуса
          in: query
          type: integer
          required: true
        - name: stop_id
          description: Идентификатор остановки
          in: query
          type: integer
          required: false
        - name: step
          description: Порядковый номер остановки на пути автобуса
          in: query
          type: integer
          required: false
      responses:
        "204":
          description: No Content
        "400":
          description: Bad request
        "500":
          description: Internal server error
