version: "3.9"
    
services:
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bus_routes
      MYSQL_USER: gxravel
      MYSQL_PASSWORD: gxravel
    ports:
      - 3308:3306

  storage:
    image: redis
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - 6378:6379
    
volumes:
  db_data: {}
  redis_data: {}
